# Generated by Django 3.2.13 on 2022-06-18 22:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='venue_image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/roibeard/image/upload/v1655578160/placeholder.jpg', max_length=255, verbose_name='image'),
        ),
    ]
